version: "2.2"
services:

  discovery:
    build: ./microservices/eurekaserver
    ports:
      - "8761:8761"
    image: erueka


  gestionreservation:
    build: ./microservices/gestionreservation
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8082:8082"
    image: "gestion_reservation"
    depends_on:
      - discovery
  gestionemploye:
    build: ./microservices/GestionEmploye
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqlemploye:3306/employeDB?autoReconnect=true&useSSL=false
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/

    ports:
      - "8083:8083"
    image: "gestion_employe"
    depends_on:
      - gestionemploye-mysql_1
      - discovery
  gestionemploye-mysql_1:
    container_name: mysqlemploye
    image: "mysql:5.6"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=employeDB
      - MYSQL_ROOT_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - 3307:3306
  gestionmenu:
    build: ./microservices/GestionMenu
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8084:8084"
    image: "gestion_menu"
    depends_on:
      - discovery
  gestionlivrasion:
    build: ./microservices/GestionLivraison
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8085:8085"
    image: "gestion_livraison"
    depends_on:
      - discovery
      - gestionemploye
      - gestionmenu
  gestioncommentaires:
    build: ./microservices/GestionCommentaires
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb_2:3306/commentairesDB?autoReconnect=true&useSSL=false
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8086:8086"
    image: "gestion_commentaires"
    depends_on:
      - gestioncommentaires-mysql_2
      - discovery
  gestioncommentaires-mysql_2:
    container_name: mysqldb_2
    image: "mysql:5.6"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=commentairesDB
      - MYSQL_ROOT_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - 3308:3306
  # node:
  #       restart: always
  #       build: ./microservices/payment
  #       ports:
  #         - 80:3000
    
  # mongo:
  #     image: mongo
  #     ports:
  #       - 27017:27017
  #     volumes:
  #       - mongodb:/data/db
  # Mongo:
  #   container_name: Mongo
  #   image: "mongo:5-focal"
  #   ports:
  #     - "27017:27017"
  #   hostname: Mongo
  #   depends_on:
  #     - "Eureka"
  # auth:
  #   container_name: auth
  #   image: "auth"
  #   build: .\MS-auth
  #   ports:
  #     - "7000:7000"
  #   hostname: auth
  #   depends_on:
  #     - "Eureka"
  #     - "Mongo"
  #   command: "node ./src/app.js"
  # apigateway:
  #   build: ./API_Gateway_Server
  #   environment:
  #     - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
  #   ports:
  #     - "8088:8088"
  #   image: apigateway
  #   depends_on:
  #     - discovery
