version: "3.9"
services:

    discovery:
      build: ./eurekaserver
      ports:
        - "8761:8761"
      image: erueka

    gestionreservation:
      build: ./gestionreservation
      environment:
        - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      ports:
        - "8082:8082"
      image: "gestion_reservation"
      depends_on:
        - discovery
    gestionemploye:
        build: ./GestionEmploye
        environment:
          - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
          - SPRING_DATASOURCE_URL=jdbc:mysql://gestionemploye-mysql_1:3306/comptes?autoReconnect=true&useSSL=false
        ports:
          - "8083:8083"
        image: "gestion_employe"
        depends_on:
          - gestionemploye-mysql_1
          - discovery
    gestionemploye-mysql_1:
      image: "mysql:8.0"
      environment:
        - MYSQL_ROOT_PASSWORD=gustofusion
        - MYSQL_DATABASE=employe
      ports:
        - 3308:3306    
    gestionmenu:
      build: ./GestionMenu
      environment:
        - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      ports:
        - "8084:8084"
      image: "gestion_menu"
      depends_on:
        - discovery
    gestioncommentaires:
      build: ./GestionCommentaires
      environment:
        - SPRING_DATASOURCE_URL=jdbc:mysql://gestioncommentaires-mysql_2:3306/comptes?autoReconnect=true&useSSL=false
        - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      ports:
        - "8086:8086"
      image: "gestion_commentaires"
      depends_on:
        - gestioncommentaires-mysql_2
        - discovery
    gestioncommentaires-mysql_2:
      image: "mysql:8.0"
      environment:
        - MYSQL_ROOT_PASSWORD=gustofusion
        - MYSQL_DATABASE=commentaires
      ports:
        - 3307:3306
    # Mongo:
    #   container_name: Mongo
    #   image: "mongo:5-focal"
    #   ports:
    #     - "27017:27017"
    #   hostname: Mongo
    #   depends_on:
    #     - "Eureka"
    # auth:
    #   container_name: auth
    #   image: "auth"
    #   build: .\MS-auth
    #   ports:
    #     - "7000:7000"
    #   hostname: auth
    #   depends_on:
    #     - "Eureka"
    #     - "Mongo"
    #   command: "node ./src/app.js"
  # apigateway:
  #   build: ./API_Gateway_Server
  #   environment:
  #     - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
  #   ports:
  #     - "8088:8088"
  #   image: apigateway
  #   depends_on:
  #     - discovery
